[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run db:generate",
  "npm run db:migrate:deploy",
  "npm run build -- --filter=server"
]

[start]
cmd = "node apps/server/dist/index.js"
